### PR TITLE
Initial ciscoconfparse commit

### PR DESCRIPTION
**Pull request by amenon128t**
This is the initial commit of cisco-conf-parse code.

### CODE REVIEW

**Review by MichaelBaj — COMMENTED** [review]
Did you intend on committing the ciscoconfparse as a submodule instead of forking it completely?

**Comment by amenon128t** [comment]
> Did you intend on committing the ciscoconfparse as a submodule instead of forking it completely?

Have added this as a submodule now. So the only commit is now the .gitmodules file. Have verified this is fine by cloning a new repo and updating the submodule.

**Comment by amenon128t** [comment]
> Do you envision never changing the ciscoconfparse code? If so, then a submodule is a fine way to go. If you feel even a little bit like you will need to make changes and they are likely not going to accept your upstream changes, then we should fork their repo and host it in our github and then you can submodule our forked copy.

I can;t say for sure. It is possible that we may enhance some of their utils if it helps us. I agree with you - we can fork and submodule it. Let me do that.

**Comment by MichaelBaj** [comment]
I cloned mpenning/ciscoconfparse into 128technology/ciscoconfparse

**Pull request merged**
